### ISSUE TITLE
How To Prefill the FB Message

### ISSUE THREAD

**Issue by LizMyers** [EddyVerbruggen/X-Services-PhoneGap-Build-Plugins-Demo#2]
I've successfully pre-populated tweets from my PhoneGap app, but the same JS + string does not work for FB. Sample messages appear identical on GitHub. Does anyone have a work-around? Thanks in advance. LM

**Comment by edwintea** [comment]
yes,I have same problem with LizMyers

**Comment by EddyVerbruggen** [comment]
Facebook doesn't allow prefilling a message - it's agains their policy.
